# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a689a2f34e9e9c7fdf3be7b60aa53b8ccda36cdcc42b1cb1707b626b1efa4a10d16187c8691202012296a1dfaaf96d97004787636f6573522affacb45082f39

test:
  secret_key_base: 8a946d034ee981064589635622b0c66178b0d6833abd998bbff2f6bdbd3e130fbd52032ed5d6be56625c6974f037b5ac6d60d6ae09937881780059d3c4123d44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
